In [1]:
import pandas as pd

Reading abalone dataset

In [2]:
df = pd.read_csv('abalone.csv')

In [3]:
df  #

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [4]:
df.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [5]:
df.tail(2)

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.296,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.495,12

In [6]:
df.describe()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [11]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

Checking Null values

In [15]:
df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

## Handling Categorical Variables

In [16]:
df

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

### Converting Categorical Variables into Numerical Variables
- Here is only one categorical variable which is Sex, we can convert it into numerical variables using Label Encoding, 
- target variable is Rings, we can use it as a numerical variable

In [17]:
df["Sex"].value_counts()

Sex
M    1528
I    1342
F    1307
Name: count, dtype: int64

### Gonna use label encoder method to convert it into numerical variables

In [22]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["Sex"] = label_encoder.fit_transform(df["Sex"])

In [23]:
df

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,2,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,2,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,0,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,0,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,2,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,2,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,0,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,2,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

### check labelEncoder mapped the categories using `label_encoder.classes_` to see the original categories

In [25]:
# Create a new encoder with original data
new_label_encoder = LabelEncoder()
original_categories = ['F', 'I', 'M']
new_label_encoder.fit(original_categories)
print("Original categories:", new_label_encoder.classes_)
print("\nMapping:")
for i, category in enumerate(new_label_encoder.classes_):
    print(f"{category} -> {i}")

Original categories: ['F' 'I' 'M']

Mapping:
F -> 0
I -> 1
M -> 2

In [26]:
df

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,2,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,2,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,0,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,0,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,2,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,2,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,0,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,2,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

## Now let's separate the features and target variable

In [27]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [28]:
 # x = df.drop(columns=["Rings"]) 
x = df.drop("Rings", axis=1)
y = df["Rings"]

In [29]:
x

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight
0,2,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,2,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,0,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,2,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,1,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...,...
4172,0,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,2,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,2,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,0,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,2,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

In [30]:
y

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

## Train Test Split

In [31]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=40)

In [33]:
len(x_train), len(y_train),

(3341, 3341)

In [34]:
len(x_test), len(y_test)

(836, 836)

In [38]:
m = 4177 * 0.2 
s = 4177 - 836
m, s

(835.4000000000001, 3341)

## Let's Train the model

In [39]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [40]:
lr.fit(x_train, y_train)

LinearRegression()

# Test Model Performance on test set

In [41]:
lr.score(x_test, y_test)

0.49853267511531485

## Predict values with newly trained model

In [54]:
demo_input = x_test.iloc[1].to_numpy()

### Predicted value

In [55]:
lr.predict([demo_input])

c:\Users\foort\Miniconda3\envs\py39_env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([8.7779035])

### Actual value

In [60]:
y_test.iloc[1]

9

### Get the full row from the dataset
full_row = df.iloc[x_test.index[0]]

In [62]:
full_row = df.iloc[x_test.index[1]]
full_row

Sex               2.0000
Length            0.4900
Diameter          0.3950
Height            0.1200
Whole weight      0.6740
Shucked weight    0.3325
Viscera weight    0.1235
Shell weight      0.1850
Rings             9.0000
Name: 3413, dtype: float64

## Now let's do the same thing using coefficients and intercept

In [63]:
lr.coef_

array([ 2.01735342e-02, -1.04176024e+00,  1.44172881e+01,  1.05664128e+01,
        9.24378738e+00, -2.09086318e+01, -9.33093791e+00,  8.28755855e+00])

In [64]:
lr.intercept_

2.62620047361011

In [65]:
lr.n_features_in_

8

In [66]:
lr.feature_names_in_

array(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight',
       'Shucked weight', 'Viscera weight', 'Shell weight'], dtype=object)

### Now let's predict the age of the abalone using the coefficients and intercept

In [69]:
lr.coef_

array([ 2.01735342e-02, -1.04176024e+00,  1.44172881e+01,  1.05664128e+01,
        9.24378738e+00, -2.09086318e+01, -9.33093791e+00,  8.28755855e+00])

In [70]:
lr.coef_[0]

0.020173534171862566

In [72]:
x_test.iloc[1]["Height"]

0.12

In [73]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [75]:
sex = x_test.iloc[1]["Sex"]
length = x_test.iloc[1]["Length"]
diameter = x_test.iloc[1]["Diameter"]
height = x_test.iloc[1]["Height"]
whole_weight = x_test.iloc[1]["Whole weight"]
shucked_weight = x_test.iloc[1]["Shucked weight"]
viscera_weight = x_test.iloc[1]["Viscera weight"]
shell_weight = x_test.iloc[1]["Shell weight"]

In [76]:
predicted_age = (
  lr.coef_[0] * sex + lr.coef_[1] * length + lr.coef_[2] * diameter + lr.coef_[3] * height + lr.coef_[4] * whole_weight + lr.coef_[5] * shucked_weight + lr.coef_[6] * viscera_weight + lr.coef_[7] * shell_weight + lr.intercept_
)

In [77]:
predicted_age

8.777903495774463

In [78]:
lr.predict([x_test.iloc[1]])

c:\Users\foort\Miniconda3\envs\py39_env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([8.7779035])